#!/usr/bin/env bash
# Quick Start Commands for MyWave Production Deployment
# Run these commands in order to deploy to production

echo "🚀 MyWave Production Readiness Quick Start"
echo "========================================="
echo ""
echo "Execute these commands in your terminal:"
echo ""
echo "1️⃣  Start Flask Application (in terminal 1):"
echo "   python main.py"
echo ""
echo "2️⃣  In another terminal (terminal 2):"
echo ""
echo "   # Seed service images"
echo "   python scripts/seed_service_images.py"
echo ""
echo "   # Test analytics logging"
echo "   python scripts/test_analytics_log.py"
echo ""
echo "   # Verify all components"
echo "   python scripts/verify_production_readiness.py"
echo ""
echo "3️⃣  Check in browser:"
echo "   - Open http://localhost:5000"
echo "   - DevTools Console should show: [CSP Monitor] Инициализирован"
echo "   - Check Google Sheets for analytics_statistics and csp_violations"
echo ""
echo "4️⃣  Monitor cache metrics (continuously):"
echo "   watch -n 2 'curl -s http://localhost:5000/api/reco/stats | python -m json.tool'"
echo ""
echo "5️⃣  Or use interactive guide:"
echo "   python scripts/start_production_components.py"
echo ""
echo "========================================="
echo "Documentation:"
echo "  - PRODUCTION_READINESS.md (full guide)"
echo "  - PRODUCTION_SUMMARY.txt (overview)"
echo ""
