"""Create blog_post and chat_message tables

Revision ID: 30bb9011ac3c
Revises: 
Create Date: 2025-04-18 14:32:24.592388

"""
from alembic import op
import sqlalchemy as sa

from migrations.migration_utils import table_names


# revision identifiers, used by Alembic.
revision = '30bb9011ac3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    tables = table_names(conn)

    if 'blog_post' not in tables:
        op.create_table(
            'blog_post',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('title', sa.String(length=200), nullable=False),
            sa.Column('teaser', sa.String(length=500), nullable=False),
            sa.Column('content', sa.Text(), nullable=False),
            sa.Column('slug', sa.String(length=100), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('slug'),
        )

    tables = table_names(conn)
    if 'chat_message' not in tables:
        fk_args = []
        if 'blog_post' in tables:
            fk_args.append(
                sa.ForeignKeyConstraint(['blog_post_id'], ['blog_post.id']),
            )
        op.create_table(
            'chat_message',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user', sa.String(length=100), nullable=False),
            sa.Column('message', sa.Text(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('blog_post_id', sa.Integer(), nullable=True),
            *fk_args,
            sa.PrimaryKeyConstraint('id'),
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message')
    op.drop_table('blog_post')
    # ### end Alembic commands ###
