"""Add Image model and BlogPost image relationship

Revision ID: b2a005fd0c4b
Revises: b2f4a6c8d9e1
Create Date: 2025-11-08 00:47:57.170567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a005fd0c4b'
down_revision = 'b2f4a6c8d9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Try to create image table if it doesn't exist
    try:
        op.create_table('image',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('orig_filename', sa.String(length=255), nullable=False),
        sa.Column('mime_type', sa.String(length=128), nullable=False),
        sa.Column('size', sa.Integer(), nullable=False),
        sa.Column('width', sa.Integer(), nullable=True),
        sa.Column('height', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('alt', sa.String(length=255), nullable=True),
        sa.Column('caption', sa.Text(), nullable=True),
        sa.Column('group', sa.String(length=64), nullable=True),
        sa.Column('order', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('optimized', sa.Boolean(), nullable=True),
        sa.Column('format', sa.String(length=32), nullable=True),
        sa.Column('focal_point', sa.String(length=32), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('image', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_image_group'), ['group'], unique=False)
    except:
        pass # Table already exists
        
    # Try to drop legacy tables if they exist
    try:
        op.drop_table('wsc_athlete_registration')
    except:
        pass
        
    try:
        op.drop_table('wsc_coach_registration')
    except:
        pass
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_blog_post_image_id', 'image', ['image_id'], ['id'])

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_booking_date_time_phone'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_booking_date_time_phone'), ['date', 'time', 'phone'])

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('image_id')

    op.create_table('wsc_coach_registration',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('club', sa.VARCHAR(length=200), nullable=True),
    sa.Column('experience_years', sa.INTEGER(), nullable=True),
    sa.Column('group_size', sa.INTEGER(), nullable=True),
    sa.Column('contacts', sa.VARCHAR(length=200), nullable=True),
    sa.Column('portfolio_links', sa.TEXT(), nullable=True),
    sa.Column('consent', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wsc_athlete_registration',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('birth_year', sa.INTEGER(), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('coach_choice', sa.VARCHAR(length=200), nullable=True),
    sa.Column('guardian_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('guardian_contacts', sa.VARCHAR(length=200), nullable=True),
    sa.Column('consents_participation', sa.BOOLEAN(), nullable=True),
    sa.Column('consents_media', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_group'))

    op.drop_table('image')
    # ### end Alembic commands ###
