"""add email to user

Revision ID: e89ecaa2c591
Revises: 30bb9011ac3c
Create Date: 2025-04-25 19:43:10.435298

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e89ecaa2c591"
down_revision = "30bb9011ac3c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint("uq_user_email", ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_email", type_="unique")
        batch_op.drop_column("email")

    # ### end Alembic commands ###
