"""add email to user

Revision ID: e89ecaa2c591
Revises: 30bb9011ac3c
Create Date: 2025-04-25 19:43:10.435298

"""
from alembic import op
import sqlalchemy as sa

from migrations.migration_utils import column_names, has_unique_constraint, table_names


# revision identifiers, used by Alembic.
revision = 'e89ecaa2c591'
down_revision = '30bb9011ac3c'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    tables = table_names(conn)

    if 'user' not in tables:
        op.create_table(
            'user',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('username', sa.String(length=50), nullable=False),
            sa.Column('email', sa.String(length=120), nullable=False),
            sa.Column('full_name', sa.String(length=120), nullable=True),
            sa.Column('password_hash', sa.String(length=128), nullable=False),
            sa.Column('is_admin', sa.Boolean(), nullable=True),
            sa.Column('role', sa.String(length=32), nullable=False, server_default='user'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('username'),
            sa.UniqueConstraint('email', name='uq_user_email'),
        )
        return

    cols = column_names(conn, 'user')
    if 'email' in cols:
        return

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('email', sa.String(length=120), nullable=False, server_default='')
        )
        if not has_unique_constraint(conn, 'user', 'uq_user_email'):
            batch_op.create_unique_constraint('uq_user_email', ['email'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
