name: Deploy to Timeweb.cloud

on:
  push:
    branches:
      - main  # Основная ветка для деплоя

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Timeweb.cloud
        env:
          SSH_PRIVATE_KEY: ~/.ssh/id_rsa
          REMOTE_USER: root
          SSH_KEY_PATH: ~/.ssh/id_rsa
          REMOTE_HOST: mywavetreaning.ru
          REMOTE_PATH: "C:\\home\\root\\mywave"
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $REMOTE_USER@$REMOTE_HOST "cd $REMOTE_PATH && git pull && systemctl restart mywave"